/**
 * Slug utilities for SEO-friendly URLs.
 * URL pattern: /{categorySlug}/{provinceSlug}/{titleSlug}-{shortId}
 */

/** Convert any text to a URL-safe hyphenated slug */
export function slugify(text) {
  if (!text) return '';
  return text
    .toString()
    .toLowerCase()
    .trim()
    .replace(/&/g, 'and')
    .replace(/[^\w\s-]/g, '')   // strip non-word chars
    .replace(/[\s_]+/g, '-')    // spaces/underscores → hyphens
    .replace(/-+/g, '-')        // collapse consecutive hyphens
    .replace(/^-+|-+$/g, '');   // trim leading/trailing hyphens
}

// ── Category mappings ─────────────────────────────────────────────────────────

export const CATEGORY_SLUGS = {
  real_estate: 'real-estate',
  vehicles:    'vehicles',
  jobs:        'jobs',
  services:    'services',
  buy_sell:    'buy-sell',
  community:   'community',
};

export const CATEGORY_LABELS = {
  real_estate: 'Real Estate',
  vehicles:    'Vehicles',
  jobs:        'Jobs',
  services:    'Services',
  buy_sell:    'Buy & Sell',
  community:   'Community',
};

export const CATEGORY_DESCRIPTIONS = {
  real_estate: 'Find apartments, houses, condos, and commercial properties for rent or sale across Canada.',
  vehicles:    'Browse cars, trucks, motorcycles, boats, and other vehicles for sale across Canada.',
  jobs:        'Discover job opportunities, part-time work, and career openings across Canada.',
  services:    'Find local services including cleaning, tutoring, photography, repairs, and more.',
  buy_sell:    'Buy and sell electronics, furniture, clothing, collectibles, and more.',
  community:   'Local events, activities, lost & found, and community announcements.',
};

/** URL slug → DB category key */
export const SLUG_TO_CATEGORY = Object.fromEntries(
  Object.entries(CATEGORY_SLUGS).map(([k, v]) => [v, k])
);

// ── Province mappings ─────────────────────────────────────────────────────────

/** Province name (as stored in DB) → URL slug */
export function provinceToSlug(province) {
  return slugify(province || 'canada');
}

/** URL province slug → Province name (as stored in DB) */
const PROVINCE_SLUG_MAP = {
  ontario:                    'Ontario',
  'british-columbia':         'British Columbia',
  alberta:                    'Alberta',
  quebec:                     'Quebec',
  manitoba:                   'Manitoba',
  saskatchewan:               'Saskatchewan',
  'nova-scotia':              'Nova Scotia',
  'new-brunswick':            'New Brunswick',
  'newfoundland-and-labrador':'Newfoundland and Labrador',
  'prince-edward-island':     'Prince Edward Island',
  'northwest-territories':    'Northwest Territories',
  yukon:                      'Yukon',
  nunavut:                    'Nunavut',
};

export function slugToProvince(slug) {
  return PROVINCE_SLUG_MAP[slug] || null;
}

// ── Listing slug helpers ──────────────────────────────────────────────────────

/**
 * Generate the slug stored in the DB.
 * Embeds the FULL UUID (32 hex chars, no hyphens) so resolution never
 * needs a DB prefix search — we always call getById with the exact UUID.
 * Example: "iPhone 13 Pro" + "f3309f30-e29b-…" → "iphone-13-pro-f3309f30e29b41d4a716446655440000"
 */
export function generateListingSlug(title, id) {
  const titleSlug   = slugify(title || 'listing');
  const uuidNoDash  = id.replace(/-/g, ''); // always 32 hex chars
  return `${titleSlug}-${uuidNoDash}`;
}

/**
 * Extract the UUID from a slug that was generated by generateListingSlug.
 * Returns a properly formatted UUID string, or null if not found.
 */
export function extractUuidFromSlug(slug) {
  const match = slug?.match(/([0-9a-f]{32})$/i);
  if (!match) return null;
  const h = match[1];
  return `${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`;
}

// ── URL builders ─────────────────────────────────────────────────────────────

/**
 * Build the full listing URL.
 * Uses DB slug if present, otherwise generates one on the fly.
 */
export function createListingUrl(listing) {
  if (!listing?.id) return '/Browse';
  const catSlug  = CATEGORY_SLUGS[listing.category] || slugify(listing.category || 'other');
  const provSlug = provinceToSlug(listing.province || 'canada');
  const slug     = listing.slug || generateListingSlug(listing.title, listing.id);
  return `/${catSlug}/${provSlug}/${slug}`;
}

/**
 * Build a category/province landing page URL.
 * /vehicles, /vehicles/ontario, etc.
 */
export function createCategoryUrl(category, province) {
  const catSlug = CATEGORY_SLUGS[category] || slugify(category || 'browse');
  if (!province) return `/${catSlug}`;
  return `/${catSlug}/${provinceToSlug(province)}`;
}
